### ISSUE TITLE
Vídeo de apresentação do projeto

### ISSUE THREAD

**Issue by Thomasdotcom** [ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe7-t1-obesity-risk#17]

**Comment by bernardocamps** [comment]
Como parte da comprovação de construção dos modelos, um vídeo de demonstração com todas as etapas de pré-processamento e de execução dos modelos deverá ser entregue. Este vídeo poderá ser do tipo screencast e é imprescindível a narração contemplando a demonstração de todas as etapas realizadas.

**Comment by bernardocamps** [comment]
Vídeos - canal privado não listado no YouTube e colocar o link - explicar a implementação passo a passo:
- Amanda: Regressão Logística
- Bernardo: Árvore de Decisão
- Eduardo: Random Forest
